default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hotel_booking_app_dev
  username: postgres
  password: Takudzwa95!
  host: localhost

test:
  <<: *default
  database: hotel_booking_app_test
  username: postgres
  password: Takudzwa95!
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
